version: "2"
services:
  shashlik-rc-server:
    image: shashlik-rc-server
    hostname: shashlik-rc-server
    container_name: shashlik-rc-server
    network_mode: host
    environment:
      ASPNETCORE_URLS: http://*:8080
    volumes:
      - ./rc.db:/app/rc.db
