version: "2"
services:
  shashlik-rc-server:
    image: 280780363/shashlik-rc-server
    hostname: shashlik-rc-server
    container_name: shashlik-rc-server
    network_mode: host    
    environment:
      # 绑定url、端口
      ASPNETCORE_URLS: http://*:8989
      # 管理员账户
      ADMIN_USER: admin
      # 管理密码
      ADMIN_PASS: 123123
      # 数据库类型: sqlite/mysql/npgsql/sqlserver
      DB_TYPE: sqlite
      # 数据库连接字符串
      DB_CONN: Data Source=./data/rc.db;
      # 数据库版本，mysql需要，默认值5.7，其他版本需要手动定义
      #DB_VERSION: "8.0"
    volumes:
      - ./data:/app/data
