name: shashlik-rc-server-docker

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: PublishProject
        run: dotnet publish ./Shashlik.RC/Shashlik.RC.csproj --configuration Release --output ./docker/dist
      - name: Docker Image Build
        run: |
          cd ./docker
          docker build -t shashlik-rc-server .
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: shashlik-rc-server
          tag_with_ref: true