name: shashlik-rc-server-docker

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: PublishProject
        run: dotnet publish ./Shashlik.RC/Shashlik.RC.csproj --configuration Release --output ./dist
      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg" -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
